export const firstNameLabel = 'Nombre';
export const lastNameLabel = 'Apellido';
export const monthLabel = 'Mes';
export const dayLabel = 'Dia';
export const yearLabel = 'Año';
export const genderMale = 'Hombre';
export const emailLabel = 'Número de celular o correo electrónico';
export const passwordLabel = 'Contraseña nueva';
export const signUpButton = 'Registrarte';